// <auto-generated />
using System;
using EntityFramework.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace EntityFramework.Migrations
{
    [DbContext(typeof(CarsCodeFirstContext))]
    [Migration("20200917225139_Manufacturer")]
    partial class Manufacturer
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("EntityFramework.Models.CodeFirstCar", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasColumnType("int(10)");

                    b.Property<string>("Colour")
                        .IsRequired()
                        .HasColumnName("colour")
                        .HasColumnType("varchar(10)")
                        .HasAnnotation("MySql:CharSet", "utf8mb4")
                        .HasAnnotation("MySql:Collation", "utf8mb4_general_ci");

                    b.Property<int>("ManufacturerID")
                        .HasColumnName("manufacturer_id")
                        .HasColumnType("int(10)");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnName("model")
                        .HasColumnType("varchar(30)")
                        .HasAnnotation("MySql:CharSet", "utf8mb4")
                        .HasAnnotation("MySql:Collation", "utf8mb4_general_ci");

                    b.Property<int>("Odometer")
                        .HasColumnName("odometer")
                        .HasColumnType("int(10)");

                    b.Property<string>("TrimLevel")
                        .IsRequired()
                        .HasColumnName("trim_level")
                        .HasColumnType("varchar(30)")
                        .HasAnnotation("MySql:CharSet", "utf8mb4")
                        .HasAnnotation("MySql:Collation", "utf8mb4_general_ci");

                    b.HasKey("ID");

                    b.HasIndex("ManufacturerID")
                        .HasName("FK_CodeFirstCar_Manufacturer");

                    b.ToTable("code_first_car");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Colour = "Black",
                            ManufacturerID = 1,
                            Model = "Corvette",
                            Odometer = 291115,
                            TrimLevel = "R/T"
                        },
                        new
                        {
                            ID = 2,
                            Colour = "Black",
                            ManufacturerID = 1,
                            Model = "Corvette",
                            Odometer = 262549,
                            TrimLevel = "Awesome"
                        },
                        new
                        {
                            ID = 3,
                            Colour = "Black",
                            ManufacturerID = 1,
                            Model = "Durango",
                            Odometer = 267443,
                            TrimLevel = "Awesome"
                        },
                        new
                        {
                            ID = 4,
                            Colour = "Black",
                            ManufacturerID = 1,
                            Model = "Fusion",
                            Odometer = 223263,
                            TrimLevel = "Awesome"
                        },
                        new
                        {
                            ID = 5,
                            Colour = "Black",
                            ManufacturerID = 1,
                            Model = "Corvette",
                            Odometer = 44779,
                            TrimLevel = "R/T"
                        },
                        new
                        {
                            ID = 6,
                            Colour = "Black",
                            ManufacturerID = 1,
                            Model = "Corvette",
                            Odometer = 23513,
                            TrimLevel = "Awesome"
                        },
                        new
                        {
                            ID = 7,
                            Colour = "Black",
                            ManufacturerID = 1,
                            Model = "Durango",
                            Odometer = 119727,
                            TrimLevel = "Awesome"
                        },
                        new
                        {
                            ID = 8,
                            Colour = "Black",
                            ManufacturerID = 1,
                            Model = "Durango",
                            Odometer = 91670,
                            TrimLevel = "R/T"
                        },
                        new
                        {
                            ID = 9,
                            Colour = "Black",
                            ManufacturerID = 1,
                            Model = "Durango",
                            Odometer = 188062,
                            TrimLevel = "R/T"
                        },
                        new
                        {
                            ID = 10,
                            Colour = "Black",
                            ManufacturerID = 1,
                            Model = "Durango",
                            Odometer = 136247,
                            TrimLevel = "R/T"
                        },
                        new
                        {
                            ID = 11,
                            Colour = "Black",
                            ManufacturerID = 1,
                            Model = "Corvette",
                            Odometer = 120518,
                            TrimLevel = "Awesome"
                        },
                        new
                        {
                            ID = 12,
                            Colour = "Black",
                            ManufacturerID = 1,
                            Model = "Fusion",
                            Odometer = 67562,
                            TrimLevel = "Awesome"
                        },
                        new
                        {
                            ID = 13,
                            Colour = "Black",
                            ManufacturerID = 1,
                            Model = "Durango",
                            Odometer = 46465,
                            TrimLevel = "High Country"
                        },
                        new
                        {
                            ID = 14,
                            Colour = "Black",
                            ManufacturerID = 1,
                            Model = "Durango",
                            Odometer = 290556,
                            TrimLevel = "R/T"
                        },
                        new
                        {
                            ID = 15,
                            Colour = "Black",
                            ManufacturerID = 1,
                            Model = "Corvette",
                            Odometer = 62913,
                            TrimLevel = "High Country"
                        },
                        new
                        {
                            ID = 16,
                            Colour = "Black",
                            ManufacturerID = 1,
                            Model = "Durango",
                            Odometer = 54111,
                            TrimLevel = "R/T"
                        },
                        new
                        {
                            ID = 17,
                            Colour = "Black",
                            ManufacturerID = 1,
                            Model = "Fusion",
                            Odometer = 289690,
                            TrimLevel = "R/T"
                        },
                        new
                        {
                            ID = 18,
                            Colour = "Black",
                            ManufacturerID = 1,
                            Model = "Corvette",
                            Odometer = 129904,
                            TrimLevel = "R/T"
                        },
                        new
                        {
                            ID = 19,
                            Colour = "Black",
                            ManufacturerID = 1,
                            Model = "Durango",
                            Odometer = 279769,
                            TrimLevel = "Awesome"
                        },
                        new
                        {
                            ID = 20,
                            Colour = "Black",
                            ManufacturerID = 1,
                            Model = "Fusion",
                            Odometer = 136970,
                            TrimLevel = "Awesome"
                        },
                        new
                        {
                            ID = 21,
                            Colour = "Black",
                            ManufacturerID = 1,
                            Model = "Corvette",
                            Odometer = 137641,
                            TrimLevel = "High Country"
                        },
                        new
                        {
                            ID = 22,
                            Colour = "Black",
                            ManufacturerID = 1,
                            Model = "Durango",
                            Odometer = 56084,
                            TrimLevel = "R/T"
                        },
                        new
                        {
                            ID = 23,
                            Colour = "Black",
                            ManufacturerID = 1,
                            Model = "Durango",
                            Odometer = 175835,
                            TrimLevel = "High Country"
                        },
                        new
                        {
                            ID = 24,
                            Colour = "Black",
                            ManufacturerID = 1,
                            Model = "Fusion",
                            Odometer = 233940,
                            TrimLevel = "Awesome"
                        },
                        new
                        {
                            ID = 25,
                            Colour = "Black",
                            ManufacturerID = 1,
                            Model = "Fusion",
                            Odometer = 112951,
                            TrimLevel = "High Country"
                        },
                        new
                        {
                            ID = 26,
                            Colour = "Black",
                            ManufacturerID = 1,
                            Model = "Durango",
                            Odometer = 83355,
                            TrimLevel = "High Country"
                        },
                        new
                        {
                            ID = 27,
                            Colour = "Black",
                            ManufacturerID = 1,
                            Model = "Corvette",
                            Odometer = 8230,
                            TrimLevel = "High Country"
                        },
                        new
                        {
                            ID = 28,
                            Colour = "Black",
                            ManufacturerID = 1,
                            Model = "Durango",
                            Odometer = 4344,
                            TrimLevel = "Awesome"
                        },
                        new
                        {
                            ID = 29,
                            Colour = "Black",
                            ManufacturerID = 1,
                            Model = "Durango",
                            Odometer = 107986,
                            TrimLevel = "High Country"
                        },
                        new
                        {
                            ID = 30,
                            Colour = "Black",
                            ManufacturerID = 1,
                            Model = "Fusion",
                            Odometer = 77053,
                            TrimLevel = "High Country"
                        },
                        new
                        {
                            ID = 31,
                            Colour = "Black",
                            ManufacturerID = 1,
                            Model = "Corvette",
                            Odometer = 151371,
                            TrimLevel = "Awesome"
                        },
                        new
                        {
                            ID = 32,
                            Colour = "Black",
                            ManufacturerID = 1,
                            Model = "Fusion",
                            Odometer = 100011,
                            TrimLevel = "High Country"
                        },
                        new
                        {
                            ID = 33,
                            Colour = "Black",
                            ManufacturerID = 1,
                            Model = "Durango",
                            Odometer = 222072,
                            TrimLevel = "R/T"
                        },
                        new
                        {
                            ID = 34,
                            Colour = "Black",
                            ManufacturerID = 1,
                            Model = "Corvette",
                            Odometer = 9770,
                            TrimLevel = "High Country"
                        },
                        new
                        {
                            ID = 35,
                            Colour = "Black",
                            ManufacturerID = 1,
                            Model = "Durango",
                            Odometer = 142387,
                            TrimLevel = "Awesome"
                        },
                        new
                        {
                            ID = 36,
                            Colour = "Black",
                            ManufacturerID = 1,
                            Model = "Corvette",
                            Odometer = 101385,
                            TrimLevel = "High Country"
                        },
                        new
                        {
                            ID = 37,
                            Colour = "Black",
                            ManufacturerID = 1,
                            Model = "Corvette",
                            Odometer = 144623,
                            TrimLevel = "High Country"
                        },
                        new
                        {
                            ID = 38,
                            Colour = "Black",
                            ManufacturerID = 1,
                            Model = "Durango",
                            Odometer = 193067,
                            TrimLevel = "R/T"
                        },
                        new
                        {
                            ID = 39,
                            Colour = "Black",
                            ManufacturerID = 1,
                            Model = "Durango",
                            Odometer = 115228,
                            TrimLevel = "Awesome"
                        },
                        new
                        {
                            ID = 40,
                            Colour = "Black",
                            ManufacturerID = 1,
                            Model = "Durango",
                            Odometer = 158672,
                            TrimLevel = "Awesome"
                        },
                        new
                        {
                            ID = 41,
                            Colour = "Black",
                            ManufacturerID = 1,
                            Model = "Fusion",
                            Odometer = 8286,
                            TrimLevel = "R/T"
                        },
                        new
                        {
                            ID = 42,
                            Colour = "Black",
                            ManufacturerID = 1,
                            Model = "Corvette",
                            Odometer = 41667,
                            TrimLevel = "R/T"
                        },
                        new
                        {
                            ID = 43,
                            Colour = "Black",
                            ManufacturerID = 1,
                            Model = "Corvette",
                            Odometer = 277842,
                            TrimLevel = "High Country"
                        },
                        new
                        {
                            ID = 44,
                            Colour = "Black",
                            ManufacturerID = 1,
                            Model = "Corvette",
                            Odometer = 182976,
                            TrimLevel = "Awesome"
                        },
                        new
                        {
                            ID = 45,
                            Colour = "Black",
                            ManufacturerID = 1,
                            Model = "Durango",
                            Odometer = 262714,
                            TrimLevel = "High Country"
                        },
                        new
                        {
                            ID = 46,
                            Colour = "Black",
                            ManufacturerID = 1,
                            Model = "Fusion",
                            Odometer = 280430,
                            TrimLevel = "Awesome"
                        },
                        new
                        {
                            ID = 47,
                            Colour = "Black",
                            ManufacturerID = 1,
                            Model = "Durango",
                            Odometer = 242136,
                            TrimLevel = "High Country"
                        },
                        new
                        {
                            ID = 48,
                            Colour = "Black",
                            ManufacturerID = 1,
                            Model = "Corvette",
                            Odometer = 70956,
                            TrimLevel = "Awesome"
                        },
                        new
                        {
                            ID = 49,
                            Colour = "Black",
                            ManufacturerID = 1,
                            Model = "Fusion",
                            Odometer = 50131,
                            TrimLevel = "R/T"
                        },
                        new
                        {
                            ID = 50,
                            Colour = "Black",
                            ManufacturerID = 1,
                            Model = "Fusion",
                            Odometer = 100157,
                            TrimLevel = "High Country"
                        });
                });

            modelBuilder.Entity("EntityFramework.Models.Manufacturer", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasColumnType("int(10)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnName("name")
                        .HasColumnType("varchar(30)")
                        .HasAnnotation("MySql:CharSet", "utf8mb4")
                        .HasAnnotation("MySql:Collation", "utf8mb4_general_ci");

                    b.Property<int?>("YearFounded")
                        .HasColumnName("year_founded")
                        .HasColumnType("int(10)");

                    b.HasKey("ID");

                    b.ToTable("manufacturer");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Name = "Chevrolet",
                            YearFounded = 1911
                        },
                        new
                        {
                            ID = 2,
                            Name = "Ford",
                            YearFounded = 1903
                        },
                        new
                        {
                            ID = 3,
                            Name = "Tesla"
                        },
                        new
                        {
                            ID = 4,
                            Name = "Dodge"
                        },
                        new
                        {
                            ID = 5,
                            Name = "Toyota",
                            YearFounded = 1937
                        },
                        new
                        {
                            ID = 6,
                            Name = "Honda",
                            YearFounded = 1946
                        },
                        new
                        {
                            ID = 7,
                            Name = "Mitsubishi"
                        },
                        new
                        {
                            ID = 8,
                            Name = "Nissan"
                        });
                });

            modelBuilder.Entity("EntityFramework.Models.CodeFirstCar", b =>
                {
                    b.HasOne("EntityFramework.Models.Manufacturer", "ManufacturerRed")
                        .WithMany("Cars")
                        .HasForeignKey("ManufacturerID")
                        .HasConstraintName("FK_CodeFirstCar_Manufacturer")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
