// <auto-generated />
using System;
using EntityFramework.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace EntityFramework.Migrations
{
    [DbContext(typeof(EmployeeContext))]
    [Migration("20200918185413_Initialcreate")]
    partial class Initialcreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("EntityFramework.Models.Employee", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasColumnType("int(10)");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnName("dateofbirth")
                        .HasColumnType("date");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnName("enddate")
                        .HasColumnType("date");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnName("firstname")
                        .HasColumnType("varchar(30)")
                        .HasMaxLength(30)
                        .HasAnnotation("MySql:CharSet", "utf8mb4")
                        .HasAnnotation("MySql:Collation", "utf8mb4_general_ci");

                    b.Property<DateTime>("HireDate")
                        .HasColumnName("hiredate")
                        .HasColumnType("date");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnName("lastname")
                        .HasColumnType("varchar(30)")
                        .HasMaxLength(30)
                        .HasAnnotation("MySql:CharSet", "utf8mb4")
                        .HasAnnotation("MySql:Collation", "utf8mb4_general_ci");

                    b.Property<int>("LocationID")
                        .HasColumnName("location_id")
                        .HasColumnType("int(10)");

                    b.HasKey("ID");

                    b.HasIndex("LocationID")
                        .HasName("FK_Employee_Location");

                    b.ToTable("employee");

                    b.HasData(
                        new
                        {
                            ID = -1,
                            DateOfBirth = new DateTime(1962, 7, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Grace",
                            HireDate = new DateTime(2007, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Thompson",
                            LocationID = -2
                        },
                        new
                        {
                            ID = -2,
                            DateOfBirth = new DateTime(1966, 4, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Michael",
                            HireDate = new DateTime(2006, 7, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Hall",
                            LocationID = -1
                        },
                        new
                        {
                            ID = -3,
                            DateOfBirth = new DateTime(1980, 2, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EndDate = new DateTime(2015, 10, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Megan",
                            HireDate = new DateTime(2006, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Ortiz",
                            LocationID = -4
                        },
                        new
                        {
                            ID = -4,
                            DateOfBirth = new DateTime(1975, 9, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Jeffrey",
                            HireDate = new DateTime(2010, 7, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Taylor",
                            LocationID = -4
                        },
                        new
                        {
                            ID = -5,
                            DateOfBirth = new DateTime(1962, 1, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "George",
                            HireDate = new DateTime(2013, 7, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Gray",
                            LocationID = -1
                        },
                        new
                        {
                            ID = -6,
                            DateOfBirth = new DateTime(1957, 3, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Susan",
                            HireDate = new DateTime(2011, 11, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Hall",
                            LocationID = -3
                        },
                        new
                        {
                            ID = -7,
                            DateOfBirth = new DateTime(1964, 3, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Anna",
                            HireDate = new DateTime(2002, 4, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Myers",
                            LocationID = -1
                        },
                        new
                        {
                            ID = -8,
                            DateOfBirth = new DateTime(1950, 5, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Jacob",
                            HireDate = new DateTime(2004, 6, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Rivera",
                            LocationID = -5
                        },
                        new
                        {
                            ID = -9,
                            DateOfBirth = new DateTime(1967, 8, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EndDate = new DateTime(2016, 10, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Theresa",
                            HireDate = new DateTime(2010, 12, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Diaz",
                            LocationID = -4
                        },
                        new
                        {
                            ID = -10,
                            DateOfBirth = new DateTime(1955, 5, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Kyle",
                            HireDate = new DateTime(2009, 10, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Morris",
                            LocationID = -4
                        },
                        new
                        {
                            ID = -11,
                            DateOfBirth = new DateTime(1952, 6, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EndDate = new DateTime(2015, 12, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Jordan",
                            HireDate = new DateTime(2005, 12, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Ramos",
                            LocationID = -5
                        },
                        new
                        {
                            ID = -12,
                            DateOfBirth = new DateTime(1966, 9, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Jordan",
                            HireDate = new DateTime(2010, 3, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Watson",
                            LocationID = -1
                        },
                        new
                        {
                            ID = -13,
                            DateOfBirth = new DateTime(1973, 9, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EndDate = new DateTime(2015, 4, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Daniel",
                            HireDate = new DateTime(2003, 9, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Peterson",
                            LocationID = -1
                        },
                        new
                        {
                            ID = -14,
                            DateOfBirth = new DateTime(1952, 3, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EndDate = new DateTime(2017, 6, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Carol",
                            HireDate = new DateTime(2002, 4, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Harris",
                            LocationID = -3
                        },
                        new
                        {
                            ID = -15,
                            DateOfBirth = new DateTime(1968, 12, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Sharon",
                            HireDate = new DateTime(2006, 5, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Sanders",
                            LocationID = -2
                        },
                        new
                        {
                            ID = -16,
                            DateOfBirth = new DateTime(1950, 1, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Mark",
                            HireDate = new DateTime(2013, 6, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Cook",
                            LocationID = -4
                        },
                        new
                        {
                            ID = -17,
                            DateOfBirth = new DateTime(1964, 2, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Grace",
                            HireDate = new DateTime(2010, 8, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Castillo",
                            LocationID = -3
                        },
                        new
                        {
                            ID = -18,
                            DateOfBirth = new DateTime(1979, 4, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EndDate = new DateTime(2018, 10, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Alexis",
                            HireDate = new DateTime(2011, 9, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Ramirez",
                            LocationID = -3
                        },
                        new
                        {
                            ID = -19,
                            DateOfBirth = new DateTime(1968, 7, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Jennifer",
                            HireDate = new DateTime(2007, 1, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Johnson",
                            LocationID = -2
                        },
                        new
                        {
                            ID = -20,
                            DateOfBirth = new DateTime(1972, 6, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Susan",
                            HireDate = new DateTime(2007, 12, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Morgan",
                            LocationID = -2
                        },
                        new
                        {
                            ID = -21,
                            DateOfBirth = new DateTime(1974, 9, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Gabriel",
                            HireDate = new DateTime(2006, 12, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Ramos",
                            LocationID = -5
                        },
                        new
                        {
                            ID = -22,
                            DateOfBirth = new DateTime(1974, 5, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EndDate = new DateTime(2015, 1, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Beverly",
                            HireDate = new DateTime(2001, 11, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Carter",
                            LocationID = -2
                        },
                        new
                        {
                            ID = -23,
                            DateOfBirth = new DateTime(1969, 11, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Amanda",
                            HireDate = new DateTime(2003, 12, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Green",
                            LocationID = -5
                        },
                        new
                        {
                            ID = -24,
                            DateOfBirth = new DateTime(1973, 3, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Bryan",
                            HireDate = new DateTime(2012, 8, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Taylor",
                            LocationID = -1
                        },
                        new
                        {
                            ID = -25,
                            DateOfBirth = new DateTime(1951, 11, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Frank",
                            HireDate = new DateTime(2008, 6, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Kelly",
                            LocationID = -4
                        },
                        new
                        {
                            ID = -26,
                            DateOfBirth = new DateTime(1974, 12, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Jessica",
                            HireDate = new DateTime(2004, 1, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Reed",
                            LocationID = -1
                        },
                        new
                        {
                            ID = -27,
                            DateOfBirth = new DateTime(1975, 6, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Christopher",
                            HireDate = new DateTime(2002, 3, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Gomez",
                            LocationID = -4
                        },
                        new
                        {
                            ID = -28,
                            DateOfBirth = new DateTime(1954, 8, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EndDate = new DateTime(2018, 10, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Beverly",
                            HireDate = new DateTime(2013, 5, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Cook",
                            LocationID = -2
                        },
                        new
                        {
                            ID = -29,
                            DateOfBirth = new DateTime(1970, 5, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Doris",
                            HireDate = new DateTime(2000, 7, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Gomez",
                            LocationID = -1
                        },
                        new
                        {
                            ID = -30,
                            DateOfBirth = new DateTime(1972, 11, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EndDate = new DateTime(2017, 6, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Denise",
                            HireDate = new DateTime(2007, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Castillo",
                            LocationID = -1
                        },
                        new
                        {
                            ID = -31,
                            DateOfBirth = new DateTime(1964, 4, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Sandra",
                            HireDate = new DateTime(2005, 1, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Thomas",
                            LocationID = -2
                        },
                        new
                        {
                            ID = -32,
                            DateOfBirth = new DateTime(1978, 9, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EndDate = new DateTime(2018, 10, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Lauren",
                            HireDate = new DateTime(2006, 11, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Castillo",
                            LocationID = -2
                        },
                        new
                        {
                            ID = -33,
                            DateOfBirth = new DateTime(1972, 3, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Andrea",
                            HireDate = new DateTime(2006, 4, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Long",
                            LocationID = -2
                        },
                        new
                        {
                            ID = -34,
                            DateOfBirth = new DateTime(1956, 4, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Melissa",
                            HireDate = new DateTime(2009, 5, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Martinez",
                            LocationID = -1
                        },
                        new
                        {
                            ID = -35,
                            DateOfBirth = new DateTime(1980, 9, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Ryan",
                            HireDate = new DateTime(2006, 12, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Castillo",
                            LocationID = -1
                        },
                        new
                        {
                            ID = -36,
                            DateOfBirth = new DateTime(1960, 6, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Albert",
                            HireDate = new DateTime(2005, 3, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Martinez",
                            LocationID = -3
                        },
                        new
                        {
                            ID = -37,
                            DateOfBirth = new DateTime(1966, 4, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Alice",
                            HireDate = new DateTime(2009, 8, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Martin",
                            LocationID = -2
                        },
                        new
                        {
                            ID = -38,
                            DateOfBirth = new DateTime(1975, 6, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EndDate = new DateTime(2018, 6, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Benjamin",
                            HireDate = new DateTime(2013, 12, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Price",
                            LocationID = -4
                        },
                        new
                        {
                            ID = -39,
                            DateOfBirth = new DateTime(1966, 9, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Jesse",
                            HireDate = new DateTime(2010, 5, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Lee",
                            LocationID = -4
                        },
                        new
                        {
                            ID = -40,
                            DateOfBirth = new DateTime(1979, 5, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Bradley",
                            HireDate = new DateTime(2005, 2, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Castillo",
                            LocationID = -3
                        },
                        new
                        {
                            ID = -41,
                            DateOfBirth = new DateTime(1965, 4, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Susan",
                            HireDate = new DateTime(2013, 9, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Gutierrez",
                            LocationID = -2
                        },
                        new
                        {
                            ID = -42,
                            DateOfBirth = new DateTime(1960, 11, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Madison",
                            HireDate = new DateTime(2001, 10, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Ross",
                            LocationID = -3
                        },
                        new
                        {
                            ID = -43,
                            DateOfBirth = new DateTime(1978, 9, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Virginia",
                            HireDate = new DateTime(2007, 8, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Wright",
                            LocationID = -2
                        },
                        new
                        {
                            ID = -44,
                            DateOfBirth = new DateTime(1970, 12, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Walter",
                            HireDate = new DateTime(2010, 9, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Jones",
                            LocationID = -1
                        },
                        new
                        {
                            ID = -45,
                            DateOfBirth = new DateTime(1957, 8, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Isabella",
                            HireDate = new DateTime(2007, 8, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Smith",
                            LocationID = -3
                        },
                        new
                        {
                            ID = -46,
                            DateOfBirth = new DateTime(1950, 5, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Ashley",
                            HireDate = new DateTime(2002, 10, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Harris",
                            LocationID = -3
                        },
                        new
                        {
                            ID = -47,
                            DateOfBirth = new DateTime(1951, 6, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Tyler",
                            HireDate = new DateTime(2012, 4, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Moore",
                            LocationID = -3
                        },
                        new
                        {
                            ID = -48,
                            DateOfBirth = new DateTime(1952, 11, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Albert",
                            HireDate = new DateTime(2011, 2, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Diaz",
                            LocationID = -1
                        },
                        new
                        {
                            ID = -49,
                            DateOfBirth = new DateTime(1960, 10, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Madison",
                            HireDate = new DateTime(2000, 1, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Edwards",
                            LocationID = -3
                        },
                        new
                        {
                            ID = -50,
                            DateOfBirth = new DateTime(1959, 5, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Danielle",
                            HireDate = new DateTime(2012, 12, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Price",
                            LocationID = -3
                        },
                        new
                        {
                            ID = -51,
                            DateOfBirth = new DateTime(1977, 9, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Gregory",
                            HireDate = new DateTime(2000, 2, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Martin",
                            LocationID = -5
                        },
                        new
                        {
                            ID = -52,
                            DateOfBirth = new DateTime(1963, 2, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Andrew",
                            HireDate = new DateTime(2010, 11, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Rivera",
                            LocationID = -4
                        },
                        new
                        {
                            ID = -53,
                            DateOfBirth = new DateTime(1959, 8, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Judith",
                            HireDate = new DateTime(2007, 4, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Brown",
                            LocationID = -2
                        },
                        new
                        {
                            ID = -54,
                            DateOfBirth = new DateTime(1951, 12, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Christina",
                            HireDate = new DateTime(2010, 9, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Walker",
                            LocationID = -5
                        },
                        new
                        {
                            ID = -55,
                            DateOfBirth = new DateTime(1959, 12, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Doris",
                            HireDate = new DateTime(2007, 6, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Sanders",
                            LocationID = -1
                        },
                        new
                        {
                            ID = -56,
                            DateOfBirth = new DateTime(1962, 12, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Diana",
                            HireDate = new DateTime(2002, 11, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Ortiz",
                            LocationID = -2
                        },
                        new
                        {
                            ID = -57,
                            DateOfBirth = new DateTime(1975, 5, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EndDate = new DateTime(2018, 12, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Joyce",
                            HireDate = new DateTime(2011, 6, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Baker",
                            LocationID = -2
                        },
                        new
                        {
                            ID = -58,
                            DateOfBirth = new DateTime(1977, 9, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Zachary",
                            HireDate = new DateTime(2001, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Nelson",
                            LocationID = -1
                        },
                        new
                        {
                            ID = -59,
                            DateOfBirth = new DateTime(1953, 11, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Zachary",
                            HireDate = new DateTime(2004, 5, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Ortiz",
                            LocationID = -4
                        },
                        new
                        {
                            ID = -60,
                            DateOfBirth = new DateTime(1964, 2, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Danielle",
                            HireDate = new DateTime(2009, 9, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Walker",
                            LocationID = -3
                        },
                        new
                        {
                            ID = -61,
                            DateOfBirth = new DateTime(1971, 12, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EndDate = new DateTime(2015, 3, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Rose",
                            HireDate = new DateTime(2007, 10, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Jimenez",
                            LocationID = -2
                        },
                        new
                        {
                            ID = -62,
                            DateOfBirth = new DateTime(1970, 3, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Susan",
                            HireDate = new DateTime(2004, 3, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Diaz",
                            LocationID = -3
                        },
                        new
                        {
                            ID = -63,
                            DateOfBirth = new DateTime(1980, 12, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Grace",
                            HireDate = new DateTime(2011, 8, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Reed",
                            LocationID = -5
                        },
                        new
                        {
                            ID = -64,
                            DateOfBirth = new DateTime(1959, 12, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Mary",
                            HireDate = new DateTime(2011, 7, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Castillo",
                            LocationID = -4
                        },
                        new
                        {
                            ID = -65,
                            DateOfBirth = new DateTime(1960, 8, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Benjamin",
                            HireDate = new DateTime(2008, 4, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Anderson",
                            LocationID = -2
                        },
                        new
                        {
                            ID = -66,
                            DateOfBirth = new DateTime(1979, 5, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Heather",
                            HireDate = new DateTime(2004, 2, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Hall",
                            LocationID = -2
                        },
                        new
                        {
                            ID = -67,
                            DateOfBirth = new DateTime(1958, 8, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Julia",
                            HireDate = new DateTime(2009, 3, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Richardson",
                            LocationID = -5
                        },
                        new
                        {
                            ID = -68,
                            DateOfBirth = new DateTime(1955, 10, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Janet",
                            HireDate = new DateTime(2011, 5, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Reed",
                            LocationID = -4
                        },
                        new
                        {
                            ID = -69,
                            DateOfBirth = new DateTime(1968, 3, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Bradley",
                            HireDate = new DateTime(2000, 12, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Martin",
                            LocationID = -1
                        },
                        new
                        {
                            ID = -70,
                            DateOfBirth = new DateTime(1965, 4, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EndDate = new DateTime(2016, 4, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Sharon",
                            HireDate = new DateTime(2006, 11, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Williams",
                            LocationID = -4
                        },
                        new
                        {
                            ID = -71,
                            DateOfBirth = new DateTime(1951, 4, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Emma",
                            HireDate = new DateTime(2000, 1, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Johnson",
                            LocationID = -3
                        },
                        new
                        {
                            ID = -72,
                            DateOfBirth = new DateTime(1971, 3, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Joyce",
                            HireDate = new DateTime(2004, 2, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Thomas",
                            LocationID = -3
                        },
                        new
                        {
                            ID = -73,
                            DateOfBirth = new DateTime(1972, 3, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Alexander",
                            HireDate = new DateTime(2006, 12, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Campbell",
                            LocationID = -1
                        },
                        new
                        {
                            ID = -74,
                            DateOfBirth = new DateTime(1977, 10, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Catherine",
                            HireDate = new DateTime(2002, 4, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Price",
                            LocationID = -1
                        },
                        new
                        {
                            ID = -75,
                            DateOfBirth = new DateTime(1976, 7, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Jacob",
                            HireDate = new DateTime(2002, 8, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Ross",
                            LocationID = -3
                        },
                        new
                        {
                            ID = -76,
                            DateOfBirth = new DateTime(1979, 1, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Terry",
                            HireDate = new DateTime(2003, 4, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Morgan",
                            LocationID = -2
                        },
                        new
                        {
                            ID = -77,
                            DateOfBirth = new DateTime(1956, 11, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Mark",
                            HireDate = new DateTime(2012, 4, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Wilson",
                            LocationID = -1
                        },
                        new
                        {
                            ID = -78,
                            DateOfBirth = new DateTime(1974, 7, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EndDate = new DateTime(2017, 10, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Christopher",
                            HireDate = new DateTime(2003, 8, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Walker",
                            LocationID = -5
                        },
                        new
                        {
                            ID = -79,
                            DateOfBirth = new DateTime(1950, 12, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EndDate = new DateTime(2016, 2, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Alexander",
                            HireDate = new DateTime(2009, 8, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Diaz",
                            LocationID = -5
                        },
                        new
                        {
                            ID = -80,
                            DateOfBirth = new DateTime(1971, 11, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Julie",
                            HireDate = new DateTime(2011, 11, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Ross",
                            LocationID = -5
                        },
                        new
                        {
                            ID = -81,
                            DateOfBirth = new DateTime(1972, 11, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Janice",
                            HireDate = new DateTime(2001, 5, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Hall",
                            LocationID = -4
                        },
                        new
                        {
                            ID = -82,
                            DateOfBirth = new DateTime(1960, 10, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Richard",
                            HireDate = new DateTime(2006, 3, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Foster",
                            LocationID = -2
                        },
                        new
                        {
                            ID = -83,
                            DateOfBirth = new DateTime(1973, 5, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Sara",
                            HireDate = new DateTime(2009, 7, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Morgan",
                            LocationID = -5
                        },
                        new
                        {
                            ID = -84,
                            DateOfBirth = new DateTime(1976, 7, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Gloria",
                            HireDate = new DateTime(2007, 2, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Lee",
                            LocationID = -1
                        },
                        new
                        {
                            ID = -85,
                            DateOfBirth = new DateTime(1956, 6, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Daniel",
                            HireDate = new DateTime(2011, 8, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Ward",
                            LocationID = -3
                        },
                        new
                        {
                            ID = -86,
                            DateOfBirth = new DateTime(1977, 10, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EndDate = new DateTime(2015, 7, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Linda",
                            HireDate = new DateTime(2003, 9, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Perez",
                            LocationID = -1
                        },
                        new
                        {
                            ID = -87,
                            DateOfBirth = new DateTime(1975, 2, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EndDate = new DateTime(2017, 3, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Jean",
                            HireDate = new DateTime(2009, 5, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Campbell",
                            LocationID = -5
                        },
                        new
                        {
                            ID = -88,
                            DateOfBirth = new DateTime(1961, 9, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EndDate = new DateTime(2017, 4, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Russell",
                            HireDate = new DateTime(2008, 8, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Walker",
                            LocationID = -4
                        },
                        new
                        {
                            ID = -89,
                            DateOfBirth = new DateTime(1972, 4, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Theresa",
                            HireDate = new DateTime(2003, 4, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Brooks",
                            LocationID = -1
                        },
                        new
                        {
                            ID = -90,
                            DateOfBirth = new DateTime(1974, 4, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Nicholas",
                            HireDate = new DateTime(2001, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Cook",
                            LocationID = -5
                        },
                        new
                        {
                            ID = -91,
                            DateOfBirth = new DateTime(1961, 1, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EndDate = new DateTime(2016, 10, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Daniel",
                            HireDate = new DateTime(2000, 12, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Reed",
                            LocationID = -5
                        },
                        new
                        {
                            ID = -92,
                            DateOfBirth = new DateTime(1968, 8, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Russell",
                            HireDate = new DateTime(2010, 12, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Morgan",
                            LocationID = -5
                        },
                        new
                        {
                            ID = -93,
                            DateOfBirth = new DateTime(1951, 3, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Gerald",
                            HireDate = new DateTime(2001, 4, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Lee",
                            LocationID = -2
                        },
                        new
                        {
                            ID = -94,
                            DateOfBirth = new DateTime(1956, 6, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Grace",
                            HireDate = new DateTime(2008, 12, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Robinson",
                            LocationID = -3
                        },
                        new
                        {
                            ID = -95,
                            DateOfBirth = new DateTime(1970, 8, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Robert",
                            HireDate = new DateTime(2009, 12, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Anderson",
                            LocationID = -1
                        },
                        new
                        {
                            ID = -96,
                            DateOfBirth = new DateTime(1978, 8, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Maria",
                            HireDate = new DateTime(2012, 9, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Ruiz",
                            LocationID = -5
                        },
                        new
                        {
                            ID = -97,
                            DateOfBirth = new DateTime(1972, 11, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Larry",
                            HireDate = new DateTime(2002, 6, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Chavez",
                            LocationID = -2
                        },
                        new
                        {
                            ID = -98,
                            DateOfBirth = new DateTime(1955, 8, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Carolyn",
                            HireDate = new DateTime(2002, 7, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Gutierrez",
                            LocationID = -2
                        },
                        new
                        {
                            ID = -99,
                            DateOfBirth = new DateTime(1970, 4, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Jeffrey",
                            HireDate = new DateTime(2000, 5, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Kelly",
                            LocationID = -1
                        },
                        new
                        {
                            ID = -100,
                            DateOfBirth = new DateTime(1966, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EndDate = new DateTime(2015, 3, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Sara",
                            HireDate = new DateTime(2002, 6, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Wilson",
                            LocationID = -2
                        });
                });

            modelBuilder.Entity("EntityFramework.Models.Location", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasColumnType("int(10)");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnName("address")
                        .HasColumnType("varchar(30)")
                        .HasMaxLength(30)
                        .HasAnnotation("MySql:CharSet", "utf8mb4")
                        .HasAnnotation("MySql:Collation", "utf8mb4_general_ci");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnName("city")
                        .HasColumnType("varchar(30)")
                        .HasMaxLength(30)
                        .HasAnnotation("MySql:CharSet", "utf8mb4")
                        .HasAnnotation("MySql:Collation", "utf8mb4_general_ci");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnName("name")
                        .HasColumnType("varchar(30)")
                        .HasMaxLength(30)
                        .HasAnnotation("MySql:CharSet", "utf8mb4")
                        .HasAnnotation("MySql:Collation", "utf8mb4_general_ci");

                    b.Property<string>("PostalCode")
                        .IsRequired()
                        .HasColumnName("postalcode")
                        .HasColumnType("char(6)")
                        .HasMaxLength(6)
                        .HasAnnotation("MySql:CharSet", "utf8mb4")
                        .HasAnnotation("MySql:Collation", "utf8mb4_general_ci");

                    b.HasKey("ID");

                    b.ToTable("location");

                    b.HasData(
                        new
                        {
                            ID = -1,
                            Address = "123 Main Street",
                            City = "Edmonton",
                            Name = "Super Duper Store",
                            PostalCode = "T6M5W2"
                        },
                        new
                        {
                            ID = -2,
                            Address = "567 Side Street",
                            City = "Vancouver",
                            Name = "Awesome Store",
                            PostalCode = "T8M2X2"
                        },
                        new
                        {
                            ID = -3,
                            Address = "246 Boulevard Street",
                            City = "Edmonton",
                            Name = "Corporate Headquarters",
                            PostalCode = "T2Y8Z2"
                        },
                        new
                        {
                            ID = -4,
                            Address = "357 Back Street",
                            City = "Calgary",
                            Name = "Silly Store",
                            PostalCode = "T9T7L2"
                        },
                        new
                        {
                            ID = -5,
                            Address = "852 Sesame Street",
                            City = "Edmonton",
                            Name = "Elmo Store",
                            PostalCode = "T9M2A9"
                        });
                });

            modelBuilder.Entity("EntityFramework.Models.Employee", b =>
                {
                    b.HasOne("EntityFramework.Models.Location", "Location")
                        .WithMany("Employees")
                        .HasForeignKey("LocationID")
                        .HasConstraintName("FK_Employee_Location")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
