// <auto-generated />
using EntityFramework.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace EntityFramework.Migrations
{
    [DbContext(typeof(CarsCodeFirstContext))]
    [Migration("20200917181349_FirstSeedRNG")]
    partial class FirstSeedRNG
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("EntityFramework.Models.CodeFirstCar", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasColumnType("int(10)");

                    b.Property<string>("Colour")
                        .IsRequired()
                        .HasColumnName("colour")
                        .HasColumnType("varchar(10)")
                        .HasAnnotation("MySql:CharSet", "utf8mb4")
                        .HasAnnotation("MySql:Collation", "utf8mb4_general_ci");

                    b.Property<string>("Manufacturer")
                        .IsRequired()
                        .HasColumnName("manufacturer")
                        .HasColumnType("varchar(30)")
                        .HasAnnotation("MySql:CharSet", "utf8mb4")
                        .HasAnnotation("MySql:Collation", "utf8mb4_general_ci");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnName("model")
                        .HasColumnType("varchar(30)")
                        .HasAnnotation("MySql:CharSet", "utf8mb4")
                        .HasAnnotation("MySql:Collation", "utf8mb4_general_ci");

                    b.Property<int>("Odometer")
                        .HasColumnName("odometer")
                        .HasColumnType("int(10)");

                    b.Property<string>("TrimLevel")
                        .IsRequired()
                        .HasColumnName("trim_level")
                        .HasColumnType("varchar(30)")
                        .HasAnnotation("MySql:CharSet", "utf8mb4")
                        .HasAnnotation("MySql:Collation", "utf8mb4_general_ci");

                    b.HasKey("ID");

                    b.ToTable("code_first_car");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Colour = "Black",
                            Manufacturer = "Chevrolet",
                            Model = "Corvette",
                            Odometer = 154513,
                            TrimLevel = "High Country"
                        },
                        new
                        {
                            ID = 2,
                            Colour = "Black",
                            Manufacturer = "Dodge",
                            Model = "Durango",
                            Odometer = 252667,
                            TrimLevel = "R/T"
                        },
                        new
                        {
                            ID = 3,
                            Colour = "Black",
                            Manufacturer = "Dodge",
                            Model = "Durango",
                            Odometer = 299940,
                            TrimLevel = "Awesome"
                        },
                        new
                        {
                            ID = 4,
                            Colour = "Black",
                            Manufacturer = "Chevrolet",
                            Model = "Fusion",
                            Odometer = 193182,
                            TrimLevel = "R/T"
                        },
                        new
                        {
                            ID = 5,
                            Colour = "Black",
                            Manufacturer = "Chevrolet",
                            Model = "Corvette",
                            Odometer = 280545,
                            TrimLevel = "High Country"
                        },
                        new
                        {
                            ID = 6,
                            Colour = "Black",
                            Manufacturer = "Dodge",
                            Model = "Corvette",
                            Odometer = 28324,
                            TrimLevel = "R/T"
                        },
                        new
                        {
                            ID = 7,
                            Colour = "Black",
                            Manufacturer = "Ford",
                            Model = "Durango",
                            Odometer = 108337,
                            TrimLevel = "R/T"
                        },
                        new
                        {
                            ID = 8,
                            Colour = "Black",
                            Manufacturer = "Dodge",
                            Model = "Durango",
                            Odometer = 171256,
                            TrimLevel = "High Country"
                        },
                        new
                        {
                            ID = 9,
                            Colour = "Black",
                            Manufacturer = "Dodge",
                            Model = "Durango",
                            Odometer = 263907,
                            TrimLevel = "High Country"
                        },
                        new
                        {
                            ID = 10,
                            Colour = "Black",
                            Manufacturer = "Chevrolet",
                            Model = "Fusion",
                            Odometer = 227925,
                            TrimLevel = "R/T"
                        },
                        new
                        {
                            ID = 11,
                            Colour = "Black",
                            Manufacturer = "Dodge",
                            Model = "Fusion",
                            Odometer = 58910,
                            TrimLevel = "Awesome"
                        },
                        new
                        {
                            ID = 12,
                            Colour = "Black",
                            Manufacturer = "Chevrolet",
                            Model = "Durango",
                            Odometer = 137403,
                            TrimLevel = "High Country"
                        },
                        new
                        {
                            ID = 13,
                            Colour = "Black",
                            Manufacturer = "Dodge",
                            Model = "Durango",
                            Odometer = 5845,
                            TrimLevel = "R/T"
                        },
                        new
                        {
                            ID = 14,
                            Colour = "Black",
                            Manufacturer = "Dodge",
                            Model = "Corvette",
                            Odometer = 245285,
                            TrimLevel = "High Country"
                        },
                        new
                        {
                            ID = 15,
                            Colour = "Black",
                            Manufacturer = "Ford",
                            Model = "Corvette",
                            Odometer = 23040,
                            TrimLevel = "R/T"
                        },
                        new
                        {
                            ID = 16,
                            Colour = "Black",
                            Manufacturer = "Ford",
                            Model = "Corvette",
                            Odometer = 290064,
                            TrimLevel = "R/T"
                        },
                        new
                        {
                            ID = 17,
                            Colour = "Black",
                            Manufacturer = "Chevrolet",
                            Model = "Corvette",
                            Odometer = 269678,
                            TrimLevel = "R/T"
                        },
                        new
                        {
                            ID = 18,
                            Colour = "Black",
                            Manufacturer = "Dodge",
                            Model = "Fusion",
                            Odometer = 80845,
                            TrimLevel = "R/T"
                        },
                        new
                        {
                            ID = 19,
                            Colour = "Black",
                            Manufacturer = "Ford",
                            Model = "Durango",
                            Odometer = 218759,
                            TrimLevel = "R/T"
                        },
                        new
                        {
                            ID = 20,
                            Colour = "Black",
                            Manufacturer = "Dodge",
                            Model = "Corvette",
                            Odometer = 84764,
                            TrimLevel = "Awesome"
                        },
                        new
                        {
                            ID = 21,
                            Colour = "Black",
                            Manufacturer = "Chevrolet",
                            Model = "Corvette",
                            Odometer = 234106,
                            TrimLevel = "High Country"
                        },
                        new
                        {
                            ID = 22,
                            Colour = "Black",
                            Manufacturer = "Chevrolet",
                            Model = "Corvette",
                            Odometer = 105159,
                            TrimLevel = "High Country"
                        },
                        new
                        {
                            ID = 23,
                            Colour = "Black",
                            Manufacturer = "Dodge",
                            Model = "Durango",
                            Odometer = 262710,
                            TrimLevel = "High Country"
                        },
                        new
                        {
                            ID = 24,
                            Colour = "Black",
                            Manufacturer = "Chevrolet",
                            Model = "Corvette",
                            Odometer = 149261,
                            TrimLevel = "Awesome"
                        },
                        new
                        {
                            ID = 25,
                            Colour = "Black",
                            Manufacturer = "Dodge",
                            Model = "Fusion",
                            Odometer = 298653,
                            TrimLevel = "Awesome"
                        },
                        new
                        {
                            ID = 26,
                            Colour = "Black",
                            Manufacturer = "Chevrolet",
                            Model = "Durango",
                            Odometer = 189482,
                            TrimLevel = "High Country"
                        },
                        new
                        {
                            ID = 27,
                            Colour = "Black",
                            Manufacturer = "Chevrolet",
                            Model = "Corvette",
                            Odometer = 294830,
                            TrimLevel = "High Country"
                        },
                        new
                        {
                            ID = 28,
                            Colour = "Black",
                            Manufacturer = "Ford",
                            Model = "Corvette",
                            Odometer = 160129,
                            TrimLevel = "High Country"
                        },
                        new
                        {
                            ID = 29,
                            Colour = "Black",
                            Manufacturer = "Chevrolet",
                            Model = "Corvette",
                            Odometer = 241541,
                            TrimLevel = "Awesome"
                        },
                        new
                        {
                            ID = 30,
                            Colour = "Black",
                            Manufacturer = "Chevrolet",
                            Model = "Durango",
                            Odometer = 20064,
                            TrimLevel = "Awesome"
                        },
                        new
                        {
                            ID = 31,
                            Colour = "Black",
                            Manufacturer = "Chevrolet",
                            Model = "Corvette",
                            Odometer = 276777,
                            TrimLevel = "R/T"
                        },
                        new
                        {
                            ID = 32,
                            Colour = "Black",
                            Manufacturer = "Dodge",
                            Model = "Fusion",
                            Odometer = 143005,
                            TrimLevel = "High Country"
                        },
                        new
                        {
                            ID = 33,
                            Colour = "Black",
                            Manufacturer = "Dodge",
                            Model = "Fusion",
                            Odometer = 253651,
                            TrimLevel = "High Country"
                        },
                        new
                        {
                            ID = 34,
                            Colour = "Black",
                            Manufacturer = "Chevrolet",
                            Model = "Fusion",
                            Odometer = 282827,
                            TrimLevel = "High Country"
                        },
                        new
                        {
                            ID = 35,
                            Colour = "Black",
                            Manufacturer = "Chevrolet",
                            Model = "Durango",
                            Odometer = 246857,
                            TrimLevel = "Awesome"
                        },
                        new
                        {
                            ID = 36,
                            Colour = "Black",
                            Manufacturer = "Ford",
                            Model = "Corvette",
                            Odometer = 11533,
                            TrimLevel = "R/T"
                        },
                        new
                        {
                            ID = 37,
                            Colour = "Black",
                            Manufacturer = "Chevrolet",
                            Model = "Durango",
                            Odometer = 258496,
                            TrimLevel = "R/T"
                        },
                        new
                        {
                            ID = 38,
                            Colour = "Black",
                            Manufacturer = "Dodge",
                            Model = "Corvette",
                            Odometer = 263363,
                            TrimLevel = "R/T"
                        },
                        new
                        {
                            ID = 39,
                            Colour = "Black",
                            Manufacturer = "Ford",
                            Model = "Fusion",
                            Odometer = 16962,
                            TrimLevel = "Awesome"
                        },
                        new
                        {
                            ID = 40,
                            Colour = "Black",
                            Manufacturer = "Ford",
                            Model = "Corvette",
                            Odometer = 100190,
                            TrimLevel = "High Country"
                        },
                        new
                        {
                            ID = 41,
                            Colour = "Black",
                            Manufacturer = "Chevrolet",
                            Model = "Fusion",
                            Odometer = 286132,
                            TrimLevel = "R/T"
                        },
                        new
                        {
                            ID = 42,
                            Colour = "Black",
                            Manufacturer = "Chevrolet",
                            Model = "Durango",
                            Odometer = 127481,
                            TrimLevel = "High Country"
                        },
                        new
                        {
                            ID = 43,
                            Colour = "Black",
                            Manufacturer = "Chevrolet",
                            Model = "Fusion",
                            Odometer = 203166,
                            TrimLevel = "Awesome"
                        },
                        new
                        {
                            ID = 44,
                            Colour = "Black",
                            Manufacturer = "Ford",
                            Model = "Corvette",
                            Odometer = 297563,
                            TrimLevel = "High Country"
                        },
                        new
                        {
                            ID = 45,
                            Colour = "Black",
                            Manufacturer = "Dodge",
                            Model = "Durango",
                            Odometer = 19528,
                            TrimLevel = "R/T"
                        },
                        new
                        {
                            ID = 46,
                            Colour = "Black",
                            Manufacturer = "Chevrolet",
                            Model = "Corvette",
                            Odometer = 182704,
                            TrimLevel = "Awesome"
                        },
                        new
                        {
                            ID = 47,
                            Colour = "Black",
                            Manufacturer = "Dodge",
                            Model = "Durango",
                            Odometer = 112555,
                            TrimLevel = "High Country"
                        },
                        new
                        {
                            ID = 48,
                            Colour = "Black",
                            Manufacturer = "Ford",
                            Model = "Corvette",
                            Odometer = 285718,
                            TrimLevel = "High Country"
                        },
                        new
                        {
                            ID = 49,
                            Colour = "Black",
                            Manufacturer = "Dodge",
                            Model = "Durango",
                            Odometer = 33337,
                            TrimLevel = "Awesome"
                        },
                        new
                        {
                            ID = 50,
                            Colour = "Black",
                            Manufacturer = "Ford",
                            Model = "Durango",
                            Odometer = 269632,
                            TrimLevel = "Awesome"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
