// <auto-generated />
using System;
using EntityFramework.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace EntityFramework.Migrations
{
    [DbContext(typeof(EmployeeContext))]
    [Migration("20200918190951_Controllers")]
    partial class Controllers
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("EntityFramework.Models.Employee", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasColumnType("int(10)");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnName("dateofbirth")
                        .HasColumnType("date");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnName("enddate")
                        .HasColumnType("date");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnName("firstname")
                        .HasColumnType("varchar(30)")
                        .HasMaxLength(30)
                        .HasAnnotation("MySql:CharSet", "utf8mb4")
                        .HasAnnotation("MySql:Collation", "utf8mb4_general_ci");

                    b.Property<DateTime>("HireDate")
                        .HasColumnName("hiredate")
                        .HasColumnType("date");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnName("lastname")
                        .HasColumnType("varchar(30)")
                        .HasMaxLength(30)
                        .HasAnnotation("MySql:CharSet", "utf8mb4")
                        .HasAnnotation("MySql:Collation", "utf8mb4_general_ci");

                    b.Property<int>("LocationID")
                        .HasColumnName("location_id")
                        .HasColumnType("int(10)");

                    b.HasKey("ID");

                    b.HasIndex("LocationID")
                        .HasName("FK_Employee_Location");

                    b.ToTable("employee");

                    b.HasData(
                        new
                        {
                            ID = -1,
                            DateOfBirth = new DateTime(1978, 8, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Natalie",
                            HireDate = new DateTime(2007, 7, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Gomez",
                            LocationID = -3
                        },
                        new
                        {
                            ID = -2,
                            DateOfBirth = new DateTime(1959, 4, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Andrea",
                            HireDate = new DateTime(2002, 6, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Lee",
                            LocationID = -3
                        },
                        new
                        {
                            ID = -3,
                            DateOfBirth = new DateTime(1980, 2, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Timothy",
                            HireDate = new DateTime(2003, 4, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Rodriguez",
                            LocationID = -2
                        },
                        new
                        {
                            ID = -4,
                            DateOfBirth = new DateTime(1973, 6, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Charlotte",
                            HireDate = new DateTime(2010, 6, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Lopez",
                            LocationID = -1
                        },
                        new
                        {
                            ID = -5,
                            DateOfBirth = new DateTime(1960, 4, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Kimberly",
                            HireDate = new DateTime(2000, 6, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Gomez",
                            LocationID = -1
                        },
                        new
                        {
                            ID = -6,
                            DateOfBirth = new DateTime(1978, 4, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EndDate = new DateTime(2018, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Isabella",
                            HireDate = new DateTime(2013, 7, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Campbell",
                            LocationID = -5
                        },
                        new
                        {
                            ID = -7,
                            DateOfBirth = new DateTime(1972, 6, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Keith",
                            HireDate = new DateTime(2014, 11, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Nelson",
                            LocationID = -2
                        },
                        new
                        {
                            ID = -8,
                            DateOfBirth = new DateTime(1969, 10, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Randy",
                            HireDate = new DateTime(2010, 2, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Ruiz",
                            LocationID = -2
                        },
                        new
                        {
                            ID = -9,
                            DateOfBirth = new DateTime(1966, 3, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Paul",
                            HireDate = new DateTime(2011, 6, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Murphy",
                            LocationID = -1
                        },
                        new
                        {
                            ID = -10,
                            DateOfBirth = new DateTime(1967, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Diana",
                            HireDate = new DateTime(2012, 9, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Gutierrez",
                            LocationID = -3
                        },
                        new
                        {
                            ID = -11,
                            DateOfBirth = new DateTime(1979, 9, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Sara",
                            HireDate = new DateTime(2005, 2, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Clark",
                            LocationID = -5
                        },
                        new
                        {
                            ID = -12,
                            DateOfBirth = new DateTime(1962, 4, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Roger",
                            HireDate = new DateTime(2010, 11, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Hernandez",
                            LocationID = -5
                        },
                        new
                        {
                            ID = -13,
                            DateOfBirth = new DateTime(1979, 1, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Barbara",
                            HireDate = new DateTime(2012, 4, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Kelly",
                            LocationID = -1
                        },
                        new
                        {
                            ID = -14,
                            DateOfBirth = new DateTime(1955, 4, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Diana",
                            HireDate = new DateTime(2012, 9, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Edwards",
                            LocationID = -5
                        },
                        new
                        {
                            ID = -15,
                            DateOfBirth = new DateTime(1962, 8, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EndDate = new DateTime(2016, 12, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Nicole",
                            HireDate = new DateTime(2012, 3, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Walker",
                            LocationID = -3
                        },
                        new
                        {
                            ID = -16,
                            DateOfBirth = new DateTime(1954, 4, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Kimberly",
                            HireDate = new DateTime(2014, 8, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Ross",
                            LocationID = -4
                        },
                        new
                        {
                            ID = -17,
                            DateOfBirth = new DateTime(1973, 12, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Sara",
                            HireDate = new DateTime(2006, 2, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Gonzales",
                            LocationID = -2
                        },
                        new
                        {
                            ID = -18,
                            DateOfBirth = new DateTime(1956, 5, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Kathryn",
                            HireDate = new DateTime(2006, 12, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Scott",
                            LocationID = -2
                        },
                        new
                        {
                            ID = -19,
                            DateOfBirth = new DateTime(1972, 12, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Logan",
                            HireDate = new DateTime(2004, 9, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Long",
                            LocationID = -1
                        },
                        new
                        {
                            ID = -20,
                            DateOfBirth = new DateTime(1974, 12, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Ronald",
                            HireDate = new DateTime(2007, 11, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Jones",
                            LocationID = -2
                        },
                        new
                        {
                            ID = -21,
                            DateOfBirth = new DateTime(1975, 6, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Roger",
                            HireDate = new DateTime(2003, 10, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Allen",
                            LocationID = -3
                        },
                        new
                        {
                            ID = -22,
                            DateOfBirth = new DateTime(1950, 3, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Charles",
                            HireDate = new DateTime(2013, 5, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Rodriguez",
                            LocationID = -2
                        },
                        new
                        {
                            ID = -23,
                            DateOfBirth = new DateTime(1955, 4, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Victoria",
                            HireDate = new DateTime(2012, 7, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Gutierrez",
                            LocationID = -2
                        },
                        new
                        {
                            ID = -24,
                            DateOfBirth = new DateTime(1963, 4, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Margaret",
                            HireDate = new DateTime(2001, 2, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Johnson",
                            LocationID = -4
                        },
                        new
                        {
                            ID = -25,
                            DateOfBirth = new DateTime(1964, 5, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Betty",
                            HireDate = new DateTime(2000, 1, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Ruiz",
                            LocationID = -3
                        },
                        new
                        {
                            ID = -26,
                            DateOfBirth = new DateTime(1967, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Timothy",
                            HireDate = new DateTime(2009, 2, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Rodriguez",
                            LocationID = -1
                        },
                        new
                        {
                            ID = -27,
                            DateOfBirth = new DateTime(1980, 3, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Sharon",
                            HireDate = new DateTime(2000, 8, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Carter",
                            LocationID = -1
                        },
                        new
                        {
                            ID = -28,
                            DateOfBirth = new DateTime(1966, 12, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EndDate = new DateTime(2017, 10, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Joyce",
                            HireDate = new DateTime(2013, 3, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Gonzales",
                            LocationID = -4
                        },
                        new
                        {
                            ID = -29,
                            DateOfBirth = new DateTime(1964, 6, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Dennis",
                            HireDate = new DateTime(2003, 9, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Rogers",
                            LocationID = -4
                        },
                        new
                        {
                            ID = -30,
                            DateOfBirth = new DateTime(1952, 11, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Sean",
                            HireDate = new DateTime(2007, 9, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Bailey",
                            LocationID = -2
                        },
                        new
                        {
                            ID = -31,
                            DateOfBirth = new DateTime(1950, 7, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Frank",
                            HireDate = new DateTime(2001, 2, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Brooks",
                            LocationID = -5
                        },
                        new
                        {
                            ID = -32,
                            DateOfBirth = new DateTime(1968, 3, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EndDate = new DateTime(2017, 3, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Nathan",
                            HireDate = new DateTime(2008, 5, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Lopez",
                            LocationID = -5
                        },
                        new
                        {
                            ID = -33,
                            DateOfBirth = new DateTime(1958, 2, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Debra",
                            HireDate = new DateTime(2000, 3, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Jackson",
                            LocationID = -3
                        },
                        new
                        {
                            ID = -34,
                            DateOfBirth = new DateTime(1963, 8, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Terry",
                            HireDate = new DateTime(2013, 12, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Brown",
                            LocationID = -3
                        },
                        new
                        {
                            ID = -35,
                            DateOfBirth = new DateTime(1957, 2, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Kimberly",
                            HireDate = new DateTime(2002, 8, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Lopez",
                            LocationID = -1
                        },
                        new
                        {
                            ID = -36,
                            DateOfBirth = new DateTime(1961, 8, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Victoria",
                            HireDate = new DateTime(2005, 4, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Gomez",
                            LocationID = -3
                        },
                        new
                        {
                            ID = -37,
                            DateOfBirth = new DateTime(1952, 8, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EndDate = new DateTime(2017, 8, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Nicholas",
                            HireDate = new DateTime(2003, 4, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Perez",
                            LocationID = -1
                        },
                        new
                        {
                            ID = -38,
                            DateOfBirth = new DateTime(1968, 12, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Kyle",
                            HireDate = new DateTime(2004, 10, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Collins",
                            LocationID = -2
                        },
                        new
                        {
                            ID = -39,
                            DateOfBirth = new DateTime(1976, 9, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Sean",
                            HireDate = new DateTime(2005, 7, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Bailey",
                            LocationID = -1
                        },
                        new
                        {
                            ID = -40,
                            DateOfBirth = new DateTime(1961, 1, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Kelly",
                            HireDate = new DateTime(2012, 8, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Flores",
                            LocationID = -2
                        },
                        new
                        {
                            ID = -41,
                            DateOfBirth = new DateTime(1961, 7, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Logan",
                            HireDate = new DateTime(2000, 8, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Harris",
                            LocationID = -2
                        },
                        new
                        {
                            ID = -42,
                            DateOfBirth = new DateTime(1952, 7, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EndDate = new DateTime(2017, 11, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Terry",
                            HireDate = new DateTime(2013, 6, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Miller",
                            LocationID = -2
                        },
                        new
                        {
                            ID = -43,
                            DateOfBirth = new DateTime(1977, 3, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Gabriel",
                            HireDate = new DateTime(2005, 5, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Taylor",
                            LocationID = -2
                        },
                        new
                        {
                            ID = -44,
                            DateOfBirth = new DateTime(1953, 4, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Jordan",
                            HireDate = new DateTime(2009, 9, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Thompson",
                            LocationID = -3
                        },
                        new
                        {
                            ID = -45,
                            DateOfBirth = new DateTime(1972, 4, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Walter",
                            HireDate = new DateTime(2004, 9, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Murphy",
                            LocationID = -4
                        },
                        new
                        {
                            ID = -46,
                            DateOfBirth = new DateTime(1960, 8, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Andrew",
                            HireDate = new DateTime(2005, 2, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Brooks",
                            LocationID = -5
                        },
                        new
                        {
                            ID = -47,
                            DateOfBirth = new DateTime(1963, 5, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Diane",
                            HireDate = new DateTime(2004, 8, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Williams",
                            LocationID = -1
                        },
                        new
                        {
                            ID = -48,
                            DateOfBirth = new DateTime(1971, 8, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Joan",
                            HireDate = new DateTime(2011, 6, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Bennet",
                            LocationID = -4
                        },
                        new
                        {
                            ID = -49,
                            DateOfBirth = new DateTime(1966, 7, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Amy",
                            HireDate = new DateTime(2008, 11, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Castillo",
                            LocationID = -1
                        },
                        new
                        {
                            ID = -50,
                            DateOfBirth = new DateTime(1969, 2, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Roy",
                            HireDate = new DateTime(2004, 3, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Gray",
                            LocationID = -3
                        },
                        new
                        {
                            ID = -51,
                            DateOfBirth = new DateTime(1958, 3, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Cynthia",
                            HireDate = new DateTime(2003, 2, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Hernandez",
                            LocationID = -5
                        },
                        new
                        {
                            ID = -52,
                            DateOfBirth = new DateTime(1964, 10, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Theresa",
                            HireDate = new DateTime(2012, 6, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Collins",
                            LocationID = -5
                        },
                        new
                        {
                            ID = -53,
                            DateOfBirth = new DateTime(1956, 3, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Ralph",
                            HireDate = new DateTime(2013, 3, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Thomas",
                            LocationID = -5
                        },
                        new
                        {
                            ID = -54,
                            DateOfBirth = new DateTime(1978, 11, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Michelle",
                            HireDate = new DateTime(2008, 8, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Davis",
                            LocationID = -4
                        },
                        new
                        {
                            ID = -55,
                            DateOfBirth = new DateTime(1954, 3, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Russell",
                            HireDate = new DateTime(2012, 5, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Gonzales",
                            LocationID = -1
                        },
                        new
                        {
                            ID = -56,
                            DateOfBirth = new DateTime(1970, 7, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Christina",
                            HireDate = new DateTime(2007, 11, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Clark",
                            LocationID = -2
                        },
                        new
                        {
                            ID = -57,
                            DateOfBirth = new DateTime(1978, 4, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Michael",
                            HireDate = new DateTime(2013, 9, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Phillips",
                            LocationID = -1
                        },
                        new
                        {
                            ID = -58,
                            DateOfBirth = new DateTime(1980, 4, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Benjamin",
                            HireDate = new DateTime(2004, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Thomas",
                            LocationID = -3
                        },
                        new
                        {
                            ID = -59,
                            DateOfBirth = new DateTime(1977, 12, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Nancy",
                            HireDate = new DateTime(2005, 5, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Wright",
                            LocationID = -5
                        },
                        new
                        {
                            ID = -60,
                            DateOfBirth = new DateTime(1967, 4, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Angela",
                            HireDate = new DateTime(2014, 3, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Collins",
                            LocationID = -5
                        },
                        new
                        {
                            ID = -61,
                            DateOfBirth = new DateTime(1973, 11, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Brandon",
                            HireDate = new DateTime(2009, 4, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Kim",
                            LocationID = -2
                        },
                        new
                        {
                            ID = -62,
                            DateOfBirth = new DateTime(1973, 2, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Louis",
                            HireDate = new DateTime(2010, 8, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Mendoza",
                            LocationID = -4
                        },
                        new
                        {
                            ID = -63,
                            DateOfBirth = new DateTime(1974, 12, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Vincent",
                            HireDate = new DateTime(2009, 7, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Young",
                            LocationID = -2
                        },
                        new
                        {
                            ID = -64,
                            DateOfBirth = new DateTime(1961, 3, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "George",
                            HireDate = new DateTime(2011, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Martin",
                            LocationID = -3
                        },
                        new
                        {
                            ID = -65,
                            DateOfBirth = new DateTime(1962, 1, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Daniel",
                            HireDate = new DateTime(2011, 10, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Garcia",
                            LocationID = -2
                        },
                        new
                        {
                            ID = -66,
                            DateOfBirth = new DateTime(1972, 5, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Gerald",
                            HireDate = new DateTime(2013, 12, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "White",
                            LocationID = -5
                        },
                        new
                        {
                            ID = -67,
                            DateOfBirth = new DateTime(1962, 4, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Christopher",
                            HireDate = new DateTime(2004, 6, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Reyes",
                            LocationID = -4
                        },
                        new
                        {
                            ID = -68,
                            DateOfBirth = new DateTime(1973, 6, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Joshua",
                            HireDate = new DateTime(2006, 11, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Reyes",
                            LocationID = -4
                        },
                        new
                        {
                            ID = -69,
                            DateOfBirth = new DateTime(1965, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EndDate = new DateTime(2017, 10, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Evelyn",
                            HireDate = new DateTime(2013, 6, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Moore",
                            LocationID = -4
                        },
                        new
                        {
                            ID = -70,
                            DateOfBirth = new DateTime(1964, 8, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Jason",
                            HireDate = new DateTime(2006, 5, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Diaz",
                            LocationID = -2
                        },
                        new
                        {
                            ID = -71,
                            DateOfBirth = new DateTime(1972, 6, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Sara",
                            HireDate = new DateTime(2003, 3, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Reyes",
                            LocationID = -3
                        },
                        new
                        {
                            ID = -72,
                            DateOfBirth = new DateTime(1977, 2, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EndDate = new DateTime(2018, 4, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Jeremy",
                            HireDate = new DateTime(2014, 9, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Robinson",
                            LocationID = -4
                        },
                        new
                        {
                            ID = -73,
                            DateOfBirth = new DateTime(1979, 9, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Henry",
                            HireDate = new DateTime(2011, 4, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Stewart",
                            LocationID = -3
                        },
                        new
                        {
                            ID = -74,
                            DateOfBirth = new DateTime(1970, 7, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EndDate = new DateTime(2017, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Susan",
                            HireDate = new DateTime(2003, 9, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Morris",
                            LocationID = -1
                        },
                        new
                        {
                            ID = -75,
                            DateOfBirth = new DateTime(1964, 3, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Shirley",
                            HireDate = new DateTime(2008, 10, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Scott",
                            LocationID = -4
                        },
                        new
                        {
                            ID = -76,
                            DateOfBirth = new DateTime(1977, 4, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Jack",
                            HireDate = new DateTime(2006, 3, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Mitchell",
                            LocationID = -4
                        },
                        new
                        {
                            ID = -77,
                            DateOfBirth = new DateTime(1965, 7, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Rachel",
                            HireDate = new DateTime(2004, 8, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Scott",
                            LocationID = -2
                        },
                        new
                        {
                            ID = -78,
                            DateOfBirth = new DateTime(1957, 10, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EndDate = new DateTime(2016, 4, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Grace",
                            HireDate = new DateTime(2005, 4, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Martin",
                            LocationID = -5
                        },
                        new
                        {
                            ID = -79,
                            DateOfBirth = new DateTime(1953, 7, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Raymond",
                            HireDate = new DateTime(2002, 12, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Adams",
                            LocationID = -3
                        },
                        new
                        {
                            ID = -80,
                            DateOfBirth = new DateTime(1959, 11, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Kelly",
                            HireDate = new DateTime(2012, 6, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Lopez",
                            LocationID = -2
                        },
                        new
                        {
                            ID = -81,
                            DateOfBirth = new DateTime(1951, 3, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Laura",
                            HireDate = new DateTime(2000, 3, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Mitchell",
                            LocationID = -3
                        },
                        new
                        {
                            ID = -82,
                            DateOfBirth = new DateTime(1963, 3, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Louis",
                            HireDate = new DateTime(2001, 4, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Myers",
                            LocationID = -2
                        },
                        new
                        {
                            ID = -83,
                            DateOfBirth = new DateTime(1959, 10, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Kathleen",
                            HireDate = new DateTime(2009, 12, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Hall",
                            LocationID = -2
                        },
                        new
                        {
                            ID = -84,
                            DateOfBirth = new DateTime(1959, 8, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EndDate = new DateTime(2018, 12, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Kenneth",
                            HireDate = new DateTime(2011, 5, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Walker",
                            LocationID = -2
                        },
                        new
                        {
                            ID = -85,
                            DateOfBirth = new DateTime(1975, 9, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Gary",
                            HireDate = new DateTime(2008, 11, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Patel",
                            LocationID = -4
                        },
                        new
                        {
                            ID = -86,
                            DateOfBirth = new DateTime(1955, 3, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Lawrence",
                            HireDate = new DateTime(2011, 6, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Smith",
                            LocationID = -2
                        },
                        new
                        {
                            ID = -87,
                            DateOfBirth = new DateTime(1955, 8, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Doris",
                            HireDate = new DateTime(2010, 7, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Scott",
                            LocationID = -4
                        },
                        new
                        {
                            ID = -88,
                            DateOfBirth = new DateTime(1976, 10, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Madison",
                            HireDate = new DateTime(2012, 8, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Morales",
                            LocationID = -1
                        },
                        new
                        {
                            ID = -89,
                            DateOfBirth = new DateTime(1964, 2, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Bradley",
                            HireDate = new DateTime(2009, 4, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Thompson",
                            LocationID = -5
                        },
                        new
                        {
                            ID = -90,
                            DateOfBirth = new DateTime(1959, 1, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Diana",
                            HireDate = new DateTime(2012, 10, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Kim",
                            LocationID = -3
                        },
                        new
                        {
                            ID = -91,
                            DateOfBirth = new DateTime(1954, 4, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Daniel",
                            HireDate = new DateTime(2011, 2, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Hernandez",
                            LocationID = -3
                        },
                        new
                        {
                            ID = -92,
                            DateOfBirth = new DateTime(1957, 10, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Jeffrey",
                            HireDate = new DateTime(2010, 11, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Carter",
                            LocationID = -5
                        },
                        new
                        {
                            ID = -93,
                            DateOfBirth = new DateTime(1970, 4, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Sean",
                            HireDate = new DateTime(2001, 4, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Long",
                            LocationID = -4
                        },
                        new
                        {
                            ID = -94,
                            DateOfBirth = new DateTime(1953, 5, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Thomas",
                            HireDate = new DateTime(2005, 1, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Campbell",
                            LocationID = -5
                        },
                        new
                        {
                            ID = -95,
                            DateOfBirth = new DateTime(1965, 8, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Randy",
                            HireDate = new DateTime(2007, 7, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Myers",
                            LocationID = -5
                        },
                        new
                        {
                            ID = -96,
                            DateOfBirth = new DateTime(1962, 9, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Judy",
                            HireDate = new DateTime(2001, 6, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Peterson",
                            LocationID = -5
                        },
                        new
                        {
                            ID = -97,
                            DateOfBirth = new DateTime(1959, 9, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Willie",
                            HireDate = new DateTime(2010, 5, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "King",
                            LocationID = -1
                        },
                        new
                        {
                            ID = -98,
                            DateOfBirth = new DateTime(1958, 7, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Carol",
                            HireDate = new DateTime(2005, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Morgan",
                            LocationID = -1
                        },
                        new
                        {
                            ID = -99,
                            DateOfBirth = new DateTime(1953, 1, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Michelle",
                            HireDate = new DateTime(2005, 1, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Wood",
                            LocationID = -2
                        },
                        new
                        {
                            ID = -100,
                            DateOfBirth = new DateTime(1961, 8, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Marilyn",
                            HireDate = new DateTime(2001, 8, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Jackson",
                            LocationID = -4
                        });
                });

            modelBuilder.Entity("EntityFramework.Models.Location", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasColumnType("int(10)");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnName("address")
                        .HasColumnType("varchar(30)")
                        .HasMaxLength(30)
                        .HasAnnotation("MySql:CharSet", "utf8mb4")
                        .HasAnnotation("MySql:Collation", "utf8mb4_general_ci");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnName("city")
                        .HasColumnType("varchar(30)")
                        .HasMaxLength(30)
                        .HasAnnotation("MySql:CharSet", "utf8mb4")
                        .HasAnnotation("MySql:Collation", "utf8mb4_general_ci");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnName("name")
                        .HasColumnType("varchar(30)")
                        .HasMaxLength(30)
                        .HasAnnotation("MySql:CharSet", "utf8mb4")
                        .HasAnnotation("MySql:Collation", "utf8mb4_general_ci");

                    b.Property<string>("PostalCode")
                        .IsRequired()
                        .HasColumnName("postalcode")
                        .HasColumnType("char(6)")
                        .HasMaxLength(6)
                        .HasAnnotation("MySql:CharSet", "utf8mb4")
                        .HasAnnotation("MySql:Collation", "utf8mb4_general_ci");

                    b.HasKey("ID");

                    b.ToTable("location");

                    b.HasData(
                        new
                        {
                            ID = -1,
                            Address = "123 Main Street",
                            City = "Edmonton",
                            Name = "Super Duper Store",
                            PostalCode = "T6M5W2"
                        },
                        new
                        {
                            ID = -2,
                            Address = "567 Side Street",
                            City = "Vancouver",
                            Name = "Awesome Store",
                            PostalCode = "T8M2X2"
                        },
                        new
                        {
                            ID = -3,
                            Address = "246 Boulevard Street",
                            City = "Edmonton",
                            Name = "Corporate Headquarters",
                            PostalCode = "T2Y8Z2"
                        },
                        new
                        {
                            ID = -4,
                            Address = "357 Back Street",
                            City = "Calgary",
                            Name = "Silly Store",
                            PostalCode = "T9T7L2"
                        },
                        new
                        {
                            ID = -5,
                            Address = "852 Sesame Street",
                            City = "Edmonton",
                            Name = "Elmo Store",
                            PostalCode = "T9M2A9"
                        });
                });

            modelBuilder.Entity("EntityFramework.Models.Employee", b =>
                {
                    b.HasOne("EntityFramework.Models.Location", "Location")
                        .WithMany("Employees")
                        .HasForeignKey("LocationID")
                        .HasConstraintName("FK_Employee_Location")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
