// <auto-generated />
using System;
using EntityFramework.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace EntityFramework.Migrations
{
    [DbContext(typeof(CarsCodeFirstContext))]
    [Migration("20200917230927_ForeignKey")]
    partial class ForeignKey
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("EntityFramework.Models.CodeFirstCar", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasColumnType("int(10)");

                    b.Property<string>("Colour")
                        .IsRequired()
                        .HasColumnName("colour")
                        .HasColumnType("varchar(10)")
                        .HasAnnotation("MySql:CharSet", "utf8mb4")
                        .HasAnnotation("MySql:Collation", "utf8mb4_general_ci");

                    b.Property<int>("ManufacturerID")
                        .HasColumnName("manufacturer_id")
                        .HasColumnType("int(10)");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnName("model")
                        .HasColumnType("varchar(30)")
                        .HasAnnotation("MySql:CharSet", "utf8mb4")
                        .HasAnnotation("MySql:Collation", "utf8mb4_general_ci");

                    b.Property<int>("Odometer")
                        .HasColumnName("odometer")
                        .HasColumnType("int(10)");

                    b.Property<string>("TrimLevel")
                        .IsRequired()
                        .HasColumnName("trim_level")
                        .HasColumnType("varchar(30)")
                        .HasAnnotation("MySql:CharSet", "utf8mb4")
                        .HasAnnotation("MySql:Collation", "utf8mb4_general_ci");

                    b.HasKey("ID");

                    b.HasIndex("ManufacturerID")
                        .HasName("FK_CodeFirstCar_Manufacturer");

                    b.ToTable("code_first_car");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Colour = "Black",
                            ManufacturerID = 1,
                            Model = "Fusion",
                            Odometer = 40653,
                            TrimLevel = "R/T"
                        },
                        new
                        {
                            ID = 2,
                            Colour = "Black",
                            ManufacturerID = 1,
                            Model = "Fusion",
                            Odometer = 107721,
                            TrimLevel = "High Country"
                        },
                        new
                        {
                            ID = 3,
                            Colour = "Black",
                            ManufacturerID = 1,
                            Model = "Fusion",
                            Odometer = 155723,
                            TrimLevel = "R/T"
                        },
                        new
                        {
                            ID = 4,
                            Colour = "Black",
                            ManufacturerID = 1,
                            Model = "Fusion",
                            Odometer = 86307,
                            TrimLevel = "High Country"
                        },
                        new
                        {
                            ID = 5,
                            Colour = "Black",
                            ManufacturerID = 1,
                            Model = "Durango",
                            Odometer = 197547,
                            TrimLevel = "R/T"
                        },
                        new
                        {
                            ID = 6,
                            Colour = "Black",
                            ManufacturerID = 1,
                            Model = "Fusion",
                            Odometer = 267839,
                            TrimLevel = "High Country"
                        },
                        new
                        {
                            ID = 7,
                            Colour = "Black",
                            ManufacturerID = 1,
                            Model = "Durango",
                            Odometer = 46158,
                            TrimLevel = "R/T"
                        },
                        new
                        {
                            ID = 8,
                            Colour = "Black",
                            ManufacturerID = 1,
                            Model = "Corvette",
                            Odometer = 258983,
                            TrimLevel = "Awesome"
                        },
                        new
                        {
                            ID = 9,
                            Colour = "Black",
                            ManufacturerID = 1,
                            Model = "Corvette",
                            Odometer = 75522,
                            TrimLevel = "Awesome"
                        },
                        new
                        {
                            ID = 10,
                            Colour = "Black",
                            ManufacturerID = 1,
                            Model = "Fusion",
                            Odometer = 169481,
                            TrimLevel = "R/T"
                        },
                        new
                        {
                            ID = 11,
                            Colour = "Black",
                            ManufacturerID = 1,
                            Model = "Durango",
                            Odometer = 56870,
                            TrimLevel = "High Country"
                        },
                        new
                        {
                            ID = 12,
                            Colour = "Black",
                            ManufacturerID = 1,
                            Model = "Fusion",
                            Odometer = 146296,
                            TrimLevel = "R/T"
                        },
                        new
                        {
                            ID = 13,
                            Colour = "Black",
                            ManufacturerID = 1,
                            Model = "Fusion",
                            Odometer = 192395,
                            TrimLevel = "High Country"
                        },
                        new
                        {
                            ID = 14,
                            Colour = "Black",
                            ManufacturerID = 1,
                            Model = "Corvette",
                            Odometer = 242895,
                            TrimLevel = "Awesome"
                        },
                        new
                        {
                            ID = 15,
                            Colour = "Black",
                            ManufacturerID = 1,
                            Model = "Durango",
                            Odometer = 185635,
                            TrimLevel = "R/T"
                        },
                        new
                        {
                            ID = 16,
                            Colour = "Black",
                            ManufacturerID = 1,
                            Model = "Durango",
                            Odometer = 60169,
                            TrimLevel = "Awesome"
                        },
                        new
                        {
                            ID = 17,
                            Colour = "Black",
                            ManufacturerID = 1,
                            Model = "Durango",
                            Odometer = 246418,
                            TrimLevel = "R/T"
                        },
                        new
                        {
                            ID = 18,
                            Colour = "Black",
                            ManufacturerID = 1,
                            Model = "Durango",
                            Odometer = 279487,
                            TrimLevel = "Awesome"
                        },
                        new
                        {
                            ID = 19,
                            Colour = "Black",
                            ManufacturerID = 1,
                            Model = "Corvette",
                            Odometer = 226404,
                            TrimLevel = "R/T"
                        },
                        new
                        {
                            ID = 20,
                            Colour = "Black",
                            ManufacturerID = 1,
                            Model = "Corvette",
                            Odometer = 81373,
                            TrimLevel = "R/T"
                        },
                        new
                        {
                            ID = 21,
                            Colour = "Black",
                            ManufacturerID = 1,
                            Model = "Corvette",
                            Odometer = 281339,
                            TrimLevel = "Awesome"
                        },
                        new
                        {
                            ID = 22,
                            Colour = "Black",
                            ManufacturerID = 1,
                            Model = "Fusion",
                            Odometer = 296012,
                            TrimLevel = "High Country"
                        },
                        new
                        {
                            ID = 23,
                            Colour = "Black",
                            ManufacturerID = 1,
                            Model = "Corvette",
                            Odometer = 62456,
                            TrimLevel = "Awesome"
                        },
                        new
                        {
                            ID = 24,
                            Colour = "Black",
                            ManufacturerID = 1,
                            Model = "Corvette",
                            Odometer = 277479,
                            TrimLevel = "High Country"
                        },
                        new
                        {
                            ID = 25,
                            Colour = "Black",
                            ManufacturerID = 1,
                            Model = "Corvette",
                            Odometer = 185311,
                            TrimLevel = "R/T"
                        },
                        new
                        {
                            ID = 26,
                            Colour = "Black",
                            ManufacturerID = 1,
                            Model = "Durango",
                            Odometer = 134490,
                            TrimLevel = "R/T"
                        },
                        new
                        {
                            ID = 27,
                            Colour = "Black",
                            ManufacturerID = 1,
                            Model = "Corvette",
                            Odometer = 285030,
                            TrimLevel = "Awesome"
                        },
                        new
                        {
                            ID = 28,
                            Colour = "Black",
                            ManufacturerID = 1,
                            Model = "Corvette",
                            Odometer = 285247,
                            TrimLevel = "R/T"
                        },
                        new
                        {
                            ID = 29,
                            Colour = "Black",
                            ManufacturerID = 1,
                            Model = "Fusion",
                            Odometer = 129002,
                            TrimLevel = "High Country"
                        },
                        new
                        {
                            ID = 30,
                            Colour = "Black",
                            ManufacturerID = 1,
                            Model = "Corvette",
                            Odometer = 6344,
                            TrimLevel = "R/T"
                        },
                        new
                        {
                            ID = 31,
                            Colour = "Black",
                            ManufacturerID = 1,
                            Model = "Fusion",
                            Odometer = 175966,
                            TrimLevel = "R/T"
                        },
                        new
                        {
                            ID = 32,
                            Colour = "Black",
                            ManufacturerID = 1,
                            Model = "Durango",
                            Odometer = 20100,
                            TrimLevel = "Awesome"
                        },
                        new
                        {
                            ID = 33,
                            Colour = "Black",
                            ManufacturerID = 1,
                            Model = "Fusion",
                            Odometer = 51696,
                            TrimLevel = "Awesome"
                        },
                        new
                        {
                            ID = 34,
                            Colour = "Black",
                            ManufacturerID = 1,
                            Model = "Durango",
                            Odometer = 3814,
                            TrimLevel = "R/T"
                        },
                        new
                        {
                            ID = 35,
                            Colour = "Black",
                            ManufacturerID = 1,
                            Model = "Fusion",
                            Odometer = 121808,
                            TrimLevel = "High Country"
                        },
                        new
                        {
                            ID = 36,
                            Colour = "Black",
                            ManufacturerID = 1,
                            Model = "Fusion",
                            Odometer = 56722,
                            TrimLevel = "High Country"
                        },
                        new
                        {
                            ID = 37,
                            Colour = "Black",
                            ManufacturerID = 1,
                            Model = "Corvette",
                            Odometer = 232073,
                            TrimLevel = "Awesome"
                        },
                        new
                        {
                            ID = 38,
                            Colour = "Black",
                            ManufacturerID = 1,
                            Model = "Corvette",
                            Odometer = 267810,
                            TrimLevel = "High Country"
                        },
                        new
                        {
                            ID = 39,
                            Colour = "Black",
                            ManufacturerID = 1,
                            Model = "Corvette",
                            Odometer = 121064,
                            TrimLevel = "High Country"
                        },
                        new
                        {
                            ID = 40,
                            Colour = "Black",
                            ManufacturerID = 1,
                            Model = "Fusion",
                            Odometer = 26378,
                            TrimLevel = "High Country"
                        },
                        new
                        {
                            ID = 41,
                            Colour = "Black",
                            ManufacturerID = 1,
                            Model = "Durango",
                            Odometer = 35499,
                            TrimLevel = "Awesome"
                        },
                        new
                        {
                            ID = 42,
                            Colour = "Black",
                            ManufacturerID = 1,
                            Model = "Corvette",
                            Odometer = 198196,
                            TrimLevel = "R/T"
                        },
                        new
                        {
                            ID = 43,
                            Colour = "Black",
                            ManufacturerID = 1,
                            Model = "Durango",
                            Odometer = 187149,
                            TrimLevel = "Awesome"
                        },
                        new
                        {
                            ID = 44,
                            Colour = "Black",
                            ManufacturerID = 1,
                            Model = "Durango",
                            Odometer = 284333,
                            TrimLevel = "R/T"
                        },
                        new
                        {
                            ID = 45,
                            Colour = "Black",
                            ManufacturerID = 1,
                            Model = "Corvette",
                            Odometer = 76033,
                            TrimLevel = "R/T"
                        },
                        new
                        {
                            ID = 46,
                            Colour = "Black",
                            ManufacturerID = 1,
                            Model = "Fusion",
                            Odometer = 70201,
                            TrimLevel = "High Country"
                        },
                        new
                        {
                            ID = 47,
                            Colour = "Black",
                            ManufacturerID = 1,
                            Model = "Durango",
                            Odometer = 236269,
                            TrimLevel = "Awesome"
                        },
                        new
                        {
                            ID = 48,
                            Colour = "Black",
                            ManufacturerID = 1,
                            Model = "Corvette",
                            Odometer = 235639,
                            TrimLevel = "Awesome"
                        },
                        new
                        {
                            ID = 49,
                            Colour = "Black",
                            ManufacturerID = 1,
                            Model = "Corvette",
                            Odometer = 144275,
                            TrimLevel = "R/T"
                        },
                        new
                        {
                            ID = 50,
                            Colour = "Black",
                            ManufacturerID = 1,
                            Model = "Fusion",
                            Odometer = 267471,
                            TrimLevel = "High Country"
                        });
                });

            modelBuilder.Entity("EntityFramework.Models.Manufacturer", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasColumnType("int(10)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnName("name")
                        .HasColumnType("varchar(30)")
                        .HasAnnotation("MySql:CharSet", "utf8mb4")
                        .HasAnnotation("MySql:Collation", "utf8mb4_general_ci");

                    b.Property<int?>("YearFounded")
                        .HasColumnName("year_founded")
                        .HasColumnType("int(10)");

                    b.HasKey("ID");

                    b.ToTable("manufacturer");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Name = "Chevrolet",
                            YearFounded = 1911
                        },
                        new
                        {
                            ID = 2,
                            Name = "Ford",
                            YearFounded = 1903
                        },
                        new
                        {
                            ID = 3,
                            Name = "Tesla"
                        },
                        new
                        {
                            ID = 4,
                            Name = "Dodge"
                        },
                        new
                        {
                            ID = 5,
                            Name = "Toyota",
                            YearFounded = 1937
                        },
                        new
                        {
                            ID = 6,
                            Name = "Honda",
                            YearFounded = 1946
                        },
                        new
                        {
                            ID = 7,
                            Name = "Mitsubishi"
                        },
                        new
                        {
                            ID = 8,
                            Name = "Nissan"
                        });
                });

            modelBuilder.Entity("EntityFramework.Models.CodeFirstCar", b =>
                {
                    b.HasOne("EntityFramework.Models.Manufacturer", "ManufacturerRed")
                        .WithMany("Cars")
                        .HasForeignKey("ManufacturerID")
                        .HasConstraintName("FK_CodeFirstCar_Manufacturer")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
