// <auto-generated />
using System;
using EntityFramework.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace EntityFramework.Migrations
{
    [DbContext(typeof(CarsCodeFirstContext))]
    partial class CarsCodeFirstContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("EntityFramework.Models.CodeFirstCar", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasColumnType("int(10)");

                    b.Property<string>("Colour")
                        .IsRequired()
                        .HasColumnName("colour")
                        .HasColumnType("varchar(10)")
                        .HasAnnotation("MySql:CharSet", "utf8mb4")
                        .HasAnnotation("MySql:Collation", "utf8mb4_general_ci");

                    b.Property<int>("ManufacturerID")
                        .HasColumnName("manufacturer_id")
                        .HasColumnType("int(10)");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnName("model")
                        .HasColumnType("varchar(30)")
                        .HasAnnotation("MySql:CharSet", "utf8mb4")
                        .HasAnnotation("MySql:Collation", "utf8mb4_general_ci");

                    b.Property<int>("Odometer")
                        .HasColumnName("odometer")
                        .HasColumnType("int(10)");

                    b.Property<string>("TrimLevel")
                        .IsRequired()
                        .HasColumnName("trim_level")
                        .HasColumnType("varchar(30)")
                        .HasAnnotation("MySql:CharSet", "utf8mb4")
                        .HasAnnotation("MySql:Collation", "utf8mb4_general_ci");

                    b.HasKey("ID");

                    b.HasIndex("ManufacturerID")
                        .HasName("FK_CodeFirstCar_Manufacturer");

                    b.ToTable("code_first_car");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Colour = "Black",
                            ManufacturerID = 1,
                            Model = "Durango",
                            Odometer = 80346,
                            TrimLevel = "R/T"
                        },
                        new
                        {
                            ID = 2,
                            Colour = "Black",
                            ManufacturerID = 1,
                            Model = "Durango",
                            Odometer = 243707,
                            TrimLevel = "Awesome"
                        },
                        new
                        {
                            ID = 3,
                            Colour = "Black",
                            ManufacturerID = 1,
                            Model = "Corvette",
                            Odometer = 271071,
                            TrimLevel = "Awesome"
                        },
                        new
                        {
                            ID = 4,
                            Colour = "Black",
                            ManufacturerID = 1,
                            Model = "Corvette",
                            Odometer = 23537,
                            TrimLevel = "R/T"
                        },
                        new
                        {
                            ID = 5,
                            Colour = "Black",
                            ManufacturerID = 1,
                            Model = "Corvette",
                            Odometer = 161778,
                            TrimLevel = "Awesome"
                        },
                        new
                        {
                            ID = 6,
                            Colour = "Black",
                            ManufacturerID = 1,
                            Model = "Corvette",
                            Odometer = 97011,
                            TrimLevel = "Awesome"
                        },
                        new
                        {
                            ID = 7,
                            Colour = "Black",
                            ManufacturerID = 1,
                            Model = "Corvette",
                            Odometer = 212876,
                            TrimLevel = "High Country"
                        },
                        new
                        {
                            ID = 8,
                            Colour = "Black",
                            ManufacturerID = 1,
                            Model = "Fusion",
                            Odometer = 125273,
                            TrimLevel = "High Country"
                        },
                        new
                        {
                            ID = 9,
                            Colour = "Black",
                            ManufacturerID = 1,
                            Model = "Durango",
                            Odometer = 39658,
                            TrimLevel = "High Country"
                        },
                        new
                        {
                            ID = 10,
                            Colour = "Black",
                            ManufacturerID = 1,
                            Model = "Corvette",
                            Odometer = 157065,
                            TrimLevel = "R/T"
                        },
                        new
                        {
                            ID = 11,
                            Colour = "Black",
                            ManufacturerID = 1,
                            Model = "Durango",
                            Odometer = 216419,
                            TrimLevel = "R/T"
                        },
                        new
                        {
                            ID = 12,
                            Colour = "Black",
                            ManufacturerID = 1,
                            Model = "Durango",
                            Odometer = 157768,
                            TrimLevel = "Awesome"
                        },
                        new
                        {
                            ID = 13,
                            Colour = "Black",
                            ManufacturerID = 1,
                            Model = "Durango",
                            Odometer = 133570,
                            TrimLevel = "R/T"
                        },
                        new
                        {
                            ID = 14,
                            Colour = "Black",
                            ManufacturerID = 1,
                            Model = "Fusion",
                            Odometer = 165855,
                            TrimLevel = "Awesome"
                        },
                        new
                        {
                            ID = 15,
                            Colour = "Black",
                            ManufacturerID = 1,
                            Model = "Durango",
                            Odometer = 107105,
                            TrimLevel = "R/T"
                        },
                        new
                        {
                            ID = 16,
                            Colour = "Black",
                            ManufacturerID = 1,
                            Model = "Durango",
                            Odometer = 171304,
                            TrimLevel = "R/T"
                        },
                        new
                        {
                            ID = 17,
                            Colour = "Black",
                            ManufacturerID = 1,
                            Model = "Durango",
                            Odometer = 181526,
                            TrimLevel = "R/T"
                        },
                        new
                        {
                            ID = 18,
                            Colour = "Black",
                            ManufacturerID = 1,
                            Model = "Corvette",
                            Odometer = 177639,
                            TrimLevel = "Awesome"
                        },
                        new
                        {
                            ID = 19,
                            Colour = "Black",
                            ManufacturerID = 1,
                            Model = "Durango",
                            Odometer = 144175,
                            TrimLevel = "Awesome"
                        },
                        new
                        {
                            ID = 20,
                            Colour = "Black",
                            ManufacturerID = 1,
                            Model = "Fusion",
                            Odometer = 273209,
                            TrimLevel = "High Country"
                        },
                        new
                        {
                            ID = 21,
                            Colour = "Black",
                            ManufacturerID = 1,
                            Model = "Fusion",
                            Odometer = 100031,
                            TrimLevel = "High Country"
                        },
                        new
                        {
                            ID = 22,
                            Colour = "Black",
                            ManufacturerID = 1,
                            Model = "Durango",
                            Odometer = 67671,
                            TrimLevel = "R/T"
                        },
                        new
                        {
                            ID = 23,
                            Colour = "Black",
                            ManufacturerID = 1,
                            Model = "Durango",
                            Odometer = 68218,
                            TrimLevel = "Awesome"
                        },
                        new
                        {
                            ID = 24,
                            Colour = "Black",
                            ManufacturerID = 1,
                            Model = "Corvette",
                            Odometer = 116901,
                            TrimLevel = "R/T"
                        },
                        new
                        {
                            ID = 25,
                            Colour = "Black",
                            ManufacturerID = 1,
                            Model = "Fusion",
                            Odometer = 95623,
                            TrimLevel = "High Country"
                        },
                        new
                        {
                            ID = 26,
                            Colour = "Black",
                            ManufacturerID = 1,
                            Model = "Corvette",
                            Odometer = 166774,
                            TrimLevel = "R/T"
                        },
                        new
                        {
                            ID = 27,
                            Colour = "Black",
                            ManufacturerID = 1,
                            Model = "Corvette",
                            Odometer = 162799,
                            TrimLevel = "Awesome"
                        },
                        new
                        {
                            ID = 28,
                            Colour = "Black",
                            ManufacturerID = 1,
                            Model = "Durango",
                            Odometer = 279482,
                            TrimLevel = "R/T"
                        },
                        new
                        {
                            ID = 29,
                            Colour = "Black",
                            ManufacturerID = 1,
                            Model = "Fusion",
                            Odometer = 144096,
                            TrimLevel = "High Country"
                        },
                        new
                        {
                            ID = 30,
                            Colour = "Black",
                            ManufacturerID = 1,
                            Model = "Corvette",
                            Odometer = 27553,
                            TrimLevel = "Awesome"
                        },
                        new
                        {
                            ID = 31,
                            Colour = "Black",
                            ManufacturerID = 1,
                            Model = "Corvette",
                            Odometer = 76060,
                            TrimLevel = "Awesome"
                        },
                        new
                        {
                            ID = 32,
                            Colour = "Black",
                            ManufacturerID = 1,
                            Model = "Durango",
                            Odometer = 211930,
                            TrimLevel = "High Country"
                        },
                        new
                        {
                            ID = 33,
                            Colour = "Black",
                            ManufacturerID = 1,
                            Model = "Corvette",
                            Odometer = 298334,
                            TrimLevel = "Awesome"
                        },
                        new
                        {
                            ID = 34,
                            Colour = "Black",
                            ManufacturerID = 1,
                            Model = "Corvette",
                            Odometer = 204611,
                            TrimLevel = "High Country"
                        },
                        new
                        {
                            ID = 35,
                            Colour = "Black",
                            ManufacturerID = 1,
                            Model = "Durango",
                            Odometer = 278476,
                            TrimLevel = "R/T"
                        },
                        new
                        {
                            ID = 36,
                            Colour = "Black",
                            ManufacturerID = 1,
                            Model = "Corvette",
                            Odometer = 200808,
                            TrimLevel = "R/T"
                        },
                        new
                        {
                            ID = 37,
                            Colour = "Black",
                            ManufacturerID = 1,
                            Model = "Corvette",
                            Odometer = 61362,
                            TrimLevel = "R/T"
                        },
                        new
                        {
                            ID = 38,
                            Colour = "Black",
                            ManufacturerID = 1,
                            Model = "Fusion",
                            Odometer = 103074,
                            TrimLevel = "Awesome"
                        },
                        new
                        {
                            ID = 39,
                            Colour = "Black",
                            ManufacturerID = 1,
                            Model = "Durango",
                            Odometer = 250223,
                            TrimLevel = "High Country"
                        },
                        new
                        {
                            ID = 40,
                            Colour = "Black",
                            ManufacturerID = 1,
                            Model = "Durango",
                            Odometer = 85491,
                            TrimLevel = "R/T"
                        },
                        new
                        {
                            ID = 41,
                            Colour = "Black",
                            ManufacturerID = 1,
                            Model = "Fusion",
                            Odometer = 25751,
                            TrimLevel = "High Country"
                        },
                        new
                        {
                            ID = 42,
                            Colour = "Black",
                            ManufacturerID = 1,
                            Model = "Corvette",
                            Odometer = 242054,
                            TrimLevel = "Awesome"
                        },
                        new
                        {
                            ID = 43,
                            Colour = "Black",
                            ManufacturerID = 1,
                            Model = "Corvette",
                            Odometer = 2613,
                            TrimLevel = "R/T"
                        },
                        new
                        {
                            ID = 44,
                            Colour = "Black",
                            ManufacturerID = 1,
                            Model = "Durango",
                            Odometer = 152370,
                            TrimLevel = "Awesome"
                        },
                        new
                        {
                            ID = 45,
                            Colour = "Black",
                            ManufacturerID = 1,
                            Model = "Durango",
                            Odometer = 164581,
                            TrimLevel = "Awesome"
                        },
                        new
                        {
                            ID = 46,
                            Colour = "Black",
                            ManufacturerID = 1,
                            Model = "Fusion",
                            Odometer = 225127,
                            TrimLevel = "High Country"
                        },
                        new
                        {
                            ID = 47,
                            Colour = "Black",
                            ManufacturerID = 1,
                            Model = "Corvette",
                            Odometer = 249004,
                            TrimLevel = "Awesome"
                        },
                        new
                        {
                            ID = 48,
                            Colour = "Black",
                            ManufacturerID = 1,
                            Model = "Fusion",
                            Odometer = 81269,
                            TrimLevel = "Awesome"
                        },
                        new
                        {
                            ID = 49,
                            Colour = "Black",
                            ManufacturerID = 1,
                            Model = "Fusion",
                            Odometer = 294220,
                            TrimLevel = "High Country"
                        },
                        new
                        {
                            ID = 50,
                            Colour = "Black",
                            ManufacturerID = 1,
                            Model = "Fusion",
                            Odometer = 28635,
                            TrimLevel = "High Country"
                        });
                });

            modelBuilder.Entity("EntityFramework.Models.Manufacturer", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasColumnType("int(10)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnName("name")
                        .HasColumnType("varchar(30)")
                        .HasAnnotation("MySql:CharSet", "utf8mb4")
                        .HasAnnotation("MySql:Collation", "utf8mb4_general_ci");

                    b.Property<int?>("YearFounded")
                        .HasColumnName("year_founded")
                        .HasColumnType("int(10)");

                    b.HasKey("ID");

                    b.ToTable("manufacturer");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Name = "Chevrolet",
                            YearFounded = 1911
                        },
                        new
                        {
                            ID = 2,
                            Name = "Ford",
                            YearFounded = 1903
                        },
                        new
                        {
                            ID = 3,
                            Name = "Tesla"
                        },
                        new
                        {
                            ID = 4,
                            Name = "Dodge"
                        },
                        new
                        {
                            ID = 5,
                            Name = "Toyota",
                            YearFounded = 1937
                        },
                        new
                        {
                            ID = 6,
                            Name = "Honda",
                            YearFounded = 1946
                        },
                        new
                        {
                            ID = 7,
                            Name = "Mitsubishi"
                        },
                        new
                        {
                            ID = 8,
                            Name = "Nissan"
                        });
                });

            modelBuilder.Entity("EntityFramework.Models.CodeFirstCar", b =>
                {
                    b.HasOne("EntityFramework.Models.Manufacturer", "ManufacturerRed")
                        .WithMany("Cars")
                        .HasForeignKey("ManufacturerID")
                        .HasConstraintName("FK_CodeFirstCar_Manufacturer")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
